### ISSUE TITLE
How to fork to edit files

### ISSUE THREAD

**Issue by laparda14** [GOOFR-Group/tank-trouble#63]
I forked this repository, but it doesn’t work right. Could you help me?

**Comment by Goncalo-Marques** [comment]
Care to explain the problem you are having?

**Comment by laparda14** [comment]
I can fork it, but I can’t edit the game file

**Comment by Goncalo-Marques** [comment]
> I can’t edit the game file

Any particular game file?

I think you were able to change the files in your fork, at least I am able to see these commits from you:
- https://github.com/laparda14/tank-trouble2/commits/main/?author=laparda14

**Comment by laparda14** [comment]
Actually, I just got to looking at the files and the deploying to pages is not running the game how did you get yours to work?

**Comment by laparda14** [comment]
I also want to play my forked “tank-trouble2” game instead of yours. How do I do this?

**Comment by laparda14** [comment]
Never mind, I figured it out.

**Comment by Goncalo-Marques** [comment]
Perfect, have fun!
